#!/bin/bash

source ~/bin/lib/dmenu_helpers.sh

brightness="0
20
40
60
80
100
save"

value=$(menu "Set: " "$brightness")

if [ -n "$value" ]; then
    if [ "$value" == "save" ]; then
        xset dpms force off
    else
        xbacklight = $value
    fi
fi

