#!/usr/bin/perl

# This script is pretty darn specific

use strict;

print "Retrieving Bus Info\n";

my $data = "";
my $dir = $ARGV[0];

if ($#ARGV + 1 == 0 || $dir eq 'n')
{
    $data = ``;
    print "";
}
elsif ($dir eq 's')
{
    $data = ``;
    print "";
}
print "########################################################################\n";

#print "$data";
printArrivals($data);

print " ## Current Time: ";
system("date +'%I:%M:%s'");

sub printArrivals
{
    my $info = @_[0];
    for (split /^/, $info) 
    {
        if ($_ =~ m/>(\d\d:\d\d)</)
        {
            print " ## $1\n";
        }
    }
}

