#!/bin/bash

file=$(lsof | ack '/tmp/Flash[^ ]*' | awk '{ print "/proc/" $2 "/fd/" $4 }' | sed 's/[rwu]$//') 
echo $file

mplayer $file $1

#mplayer $(d=/proc/$(pidof plugin-container)/fd; ls --color=no  -l $d | gawk '/\/tmp\/Flash/ {print "'$d'/" $9}' ) 
# If vidya exists
#if [ -f /tmp/Flash* ]
#then
    #mplayer -cache 256 /tmp/Flash*

#else
    #echo "No video found"
#fi

