#!/bin/sh
#
# ~/.xinitrc
#

#if [ -d /etc/X11/xinit/xinitrc.d ]; then
#  for f in /etc/X11/xinit/xinitrc.d/*; do
#    [ -x "$f" ] && . "$f"
#  done
#  unset f
#fi

# xsettings
xrdb ~/.Xresources &
xset fp+ /usr/share/fonts/local &
xset r rate 250 30 & # Keyboard repeat rate
xset +dpms &
xset dpms 0 0 600 &

# Set Mouse Pointer. xmonad does not do this
#xsetroot -cursor_name left_ptr &

# Allow us to kill X with the standard keys
setxkbmap -option terminate:ctrl_alt_bksp &
xmodmap -e "keycode 135 = Menu" &
xmodmap -e "keysym Menu = Super_R" &
#xmodmap -e "!add Super = Super_r"

# Monitors
#xrandr --output LVDS1 --mode 1280x800
#xrandr --output LVDS1 --mode 1280x800 --left-of VGA1 --primary
#xrandr --output VGA1  --mode 1440x900
xrandr -o 0

# Set Background
# eval $(cat $HOME/.fehbg) &
#python ~/bin/randwall &

# start terminal emulation daemon
#/usr/bin/urxvtd -q -o -f &

# clipboard synching
#/usr/bin/autocutsel -fork &
#/usr/bin/autocutsel -selection PRIMARY -fork &

# Start Window Manager
# exec startfluxbox
# exec openbox-session
# exec awesome
#exec dwm
#exec xmonad

