#!/bin/sh

N=${1:-13}
case $N in *[!0-9]*) echo >&2 "$0: error: $N: NaN"; exit 1; esac

while read -r line
do

    i=0; while [ $i -lt ${#line} ]
    do

        eval '
            c=${line#'$(j=0; while [ $j -lt $i ]; do printf \?; j=$((j+1)); done)'}
            c=${c%'$(j=0; while [ $j -lt $((${#line}-i-1)) ]; do printf \?; j=$((j+1)); done)'}
        '

        noconv=false
        caps=false

        case $c in
        a) n=00 ;; b) n=01 ;; c) n=02 ;; d) n=03 ;; e) n=04 ;; f) n=05 ;; g) n=06 ;; h) n=07 ;;
        i) n=08 ;; j) n=09 ;; k) n=10 ;; l) n=11 ;; m) n=12 ;; n) n=13 ;; o) n=14 ;; p) n=15 ;;
        q) n=16 ;; r) n=17 ;; s) n=18 ;; t) n=19 ;; u) n=20 ;; v) n=21 ;; w) n=22 ;; x) n=23 ;;
        y) n=24 ;; z) n=25 ;;

        *)
            caps=true
            case $c in
            a) n=00 ;; b) n=01 ;; c) n=02 ;; d) n=03 ;; e) n=04 ;; f) n=05 ;; g) n=06 ;; h) n=07 ;;
            i) n=08 ;; j) n=09 ;; k) n=10 ;; l) n=11 ;; m) n=12 ;; n) n=13 ;; o) n=14 ;; p) n=15 ;;
            q) n=16 ;; r) n=17 ;; s) n=18 ;; t) n=19 ;; u) n=20 ;; v) n=21 ;; w) n=22 ;; x) n=23 ;;
            y) n=24 ;; z) n=25 ;;
            *) noconv=true
            esac

        esac

        if $noconv
        then printf %s "$c"
        else

            n=$(( (n+N)%26 ))

            if $caps
            then case $n in
                 0) printf A ;;  1) printf B ;;  2) printf C ;;  3) printf D ;;  4) printf E ;;  5) printf F ;;
                 6) printf G ;;  7) printf H ;;  8) printf I ;;  9) printf J ;; 10) printf K ;; 11) printf L ;;
                12) printf M ;; 13) printf N ;; 14) printf O ;; 15) printf P ;; 16) printf Q ;; 17) printf R ;;
                18) printf S ;; 19) printf T ;; 20) printf U ;; 21) printf V ;; 22) printf W ;; 23) printf X ;;
                24) printf Y ;; 25) printf Z ;;
            esac else case $n in
                 0) printf a ;;  1) printf b ;;  2) printf c ;;  3) printf d ;;  4) printf e ;;  5) printf f ;;
                 6) printf g ;;  7) printf h ;;  8) printf i ;;  9) printf j ;; 10) printf k ;; 11) printf l ;;
                12) printf m ;; 13) printf n ;; 14) printf o ;; 15) printf p ;; 16) printf q ;; 17) printf r ;;
                18) printf s ;; 19) printf t ;; 20) printf u ;; 21) printf v ;; 22) printf w ;; 23) printf x ;;
                24) printf y ;; 25) printf z ;;
            esac fi

        fi

        i=$((i+1))

    done

    echo

done
