#!/bin/bash

source ~/bin/lib/dmenu_helpers.sh

mainMenu="[Shutdown]
[Reboot]
[Sleep]
[Cancel]"
#[Hibernate] broken because i have no swap space

pauseMenu="now
+60
+45
+30
+15
+10
+5
+3
+2
+1"

action=$(menu "Action: " "$mainMenu")
[ -z "$action" ] && exit

case "$action" in
    '[Shutdown]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit
        command="sudo shutdown -h $pauseTime"
    ;;
    '[Reboot]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit
        command="sudo shutdown -r $pauseTime"
    ;;
    '[Sleep]')
        command="sudo pm-suspend"
    ;;
    '[Hibernate]')
        command="sudo pm-hibernate"
    ;;
    '[Cancel]')
        command="sudo shutdown -c"
    ;;
esac

#echo "$command"
$($command)

