#!/bin/sh
#AccuWeather weather script from rss feed

#METRIC=0 #Should be 0 or 1; 0 for F, 1 for C

#if [ -z $1 ]; then
#    echo "USAGE: weather.sh <Location Code or City Name>"
#    exit 0;
#fi

#curl -s http://rss.accuweather.com/rss/liveweather_rss.asp\?metric\=${METRIC}\&locCode\=$1 | perl -ne 'if (/Currently/) {chomp;/\<title\>Currently: (.*)?\<\/title\>/; print "$1"; }'

curl -s "http://api.wunderground.com/auto/wui/geo/ForecastXML/index.xml?query=${@:-98144}" |\
perl -ne '/<title>([^<]+)/&&printf "\x1B[0;34m%s\x1B[0m: ",$1;/<fcttext>([^<]+)/&&print $1,"\n"'

