#! /bin/sh

SYSFS_BACKLIGHT=/sys/class/backlight/acpi_video0
BRIGHTNESS_INTERFACE=$SYSFS_BACKLIGHT/brightness
ACTUAL_BRIGHTNESS_VALUE=$SYSFS_BACKLIGHT/actual_brightness

if [ $# -gt 1 ]
then
    echo "usage: $0 [[+|-]value]"
fi

if [ $# -eq 0 ]
then
    cat $ACTUAL_BRIGHTNESS_VALUE
else
    case $1 in
        -*|+*)
            actual_value=$(cat $ACTUAL_BRIGHTNESS_VALUE)
            new_value=$(($actual_value + $1))
            echo $new_value > $BRIGHTNESS_INTERFACE;;
        *)
            echo $1 > $BRIGHTNESS_INTERFACE;;
    esac
fi
