#!/bin/bash
#
# dvolbar - OSD Volume utility
#

#Customize this stuff
IF="Master"
SECS="1"

FONT="Droid Sans-8"
BG="#1a1a1a"
FG="#9ab8c2"
XPOS="500"
YPOS="380"
WIDTH="280"
HEIGHT=20

BARWIDTH="228"
BARHEIGHT=8

#Probably do not customize
PIPE="/tmp/dvolpipe"

err() {
  echo "$1"
  exit 1
}

usage() {
  echo "usage: dvol [option] [argument]"
  echo
  echo "Options:"
  echo "     -i, --increase - increase volume by \`argument'"
  echo "     -d, --decrease - decrease volume by \`argument'"
  echo "     -t, --toggle   - toggle mute on and off"
  echo "     -h, --help     - display this"
  exit
}

#Argument Parsing
case "$1" in
  '-i'|'--increase')
    [ -z "$2" ] && err "No argument specified for increase."
    AMIXARG="${2}%+"
    ;;
  '-d'|'--decrease')
    [ -z "$2" ] && err "No argument specified for decrease."
    AMIXARG="${2}%-"
    ;;
  '-t'|'--toggle')
    AMIXARG="toggle"
    ;;
  ''|'-h'|'--help')
    usage
    ;;
  *)
    err "Unrecognized option \`$1', see dvol --help"
    ;;
esac

#Actual volume changing (readability low)
AMIXOUT="$(amixer set "$IF" "$AMIXARG" | tail -n 1)"
MUTE="$(cut -d '[' -f 4 <<<"$AMIXOUT")"
if [ "$MUTE" = "off]" ]; then
  VOL="0"
else
  VOL="$(cut -d '[' -f 2 <<<"$AMIXOUT" | sed 's/%.*//g')"
fi

#Using named pipe to determine whether previous call still exists
#Also prevents multiple volume bar instances
#if [ ! -e "$PIPE" ]; then
#  mkfifo "$PIPE"
#  (dzen2 -x "$XPOS" -y "$YPOS" -tw "$WIDTH" -h "$HEIGHT" -fn "$FONT" -bg "$BG" -fg "$FG" -e 'onstart=uncollapse' < "$PIPE" 
#   rm -f "$PIPE") &
#fi

#Feed the pipe!
#(echo "Vol:$VOL" $(echo "$VOL" | gdbar -w "$BARWIDTH" -h "$BARHEIGHT" -bg "$BG" -fg "$FG") ; sleep "$SECS") > "$PIPE"
#(echo "Vol:" $(echo "$VOL" | dbar ); sleep "$SECS") > "$PIPE"
