#!/usr/bin/env python

import os
import sys

import subprocess

import time

def test(p):
    while 1:
        print p.strip()
        t0 = time.time()
        command = raw_input("Retype: ")
        if command == '/next':
            print
            break
        if command == '/quit' or command == '/exit':
            sys.exit()
        if command == '/save':
            savefilename = '/home/sanford/tmp/test_pass'
            savefile = open(savefilename, 'a')
            savefile.write(p)
            savefile.close()
            print "saved password"
        print "time: %.2f" % (time.time() - t0)
        print
    return



filename = '/tmp/pass'
subprocess.Popen(['/home/sanford/bin/genpass', '-sun', '-q100', '5 > /tmp/pass'])

file = open(filename)
for password in file:
    test(password)
file.close()


