#!/bin/bash

source /home/sanford/bin/lib/dmenu_helpers.sh

mainMenu="[Chapter]
[DvdNav]
[Nav+MouseMovement]"

action=$(menu "Options:" "$mainMenu")
case "$action" in
    *'Chapter'*)
        chapter=`menu "Chapter #:"`
        $(mplayer dvd://$chapter)
    ;;
    *'DvdNav'*)
        $(mplayer dvdnav://)
    ;;
    *'Nav+MouseMovement'*)
        $(mplayer -mouse-movements dvdnav://)
    ;;
esac

