#!/bin/bash

source /home/sanford/bin/lib/dmenu_helpers.sh

# Menu Items
options="[Laptop]
[External]
[Two]
[On]
[Off]"

action=$(menu "Display:" "$options")
case "$action" in
    *'Laptop'*)
        xrandr --output LVDS1 --mode 1280x800
        xrandr --output VGA1 --off
    ;;
    *'External'*)
        xrandr --output LVDS1 --off
        xrandr --output VGA1 --mode 1440x900
    ;;
    *'AddRight'*)
        xrandr --output LVDS1 --mode 1280x800 --left-of VGA1 --primary
        xrandr --output VGA1 --mode 1440x900
    ;;
    *'AddLeft'*)
        xrandr --output LVDS1 --mode 1280x800 --right-of VGA1 --primary
        xrandr --output VGA1 --mode 1440x900
    ;;
    *'On'*)
        xset dpms force on
    ;;
    *'Off'*)
        xset dpms force off
    ;;
esac

