#!/bin/bash

source /home/sanford/bin/lib/dmenu_helpers.sh

mainMenu="[Shutdown]
[Reboot]
[Sleep]
[Lock]
[Cancel]"
#[Hibernate] #defunct

pauseMenu="now
+60
+45
+30
+15
+10
+5
+3
+2
+1"

action=$(menu "Option: " "$mainMenu")
[ -z "$action" ] && exit

case "$action" in
    '[Shutdown]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit
        command="sudo shutdown -h $pauseTime"
    ;;
    '[Reboot]')
        pauseTime=$(menu "Pause:" "$pauseMenu")
        [ -z "$pauseTime" ] && exit
        command="sudo shutdown -r $pauseTime"
    ;;
    '[Sleep]')
        command="sudo /etc/acpi/handler.sh button/sleep SLPB 00000000 K"
    ;;
    '[Lock]')
        command="slock"
    ;;
    '[Hibernate]')
        command="sudo pm-hibernate"
    ;;
    '[Cancel]')
        command="sudo shutdown -c"
    ;;
esac

#echo "$command"
$($command)

